MONGODB_HOST: mongodb-{{ env }}.daws86.fun # mongodb-dev.daws86.fun
REDIS_HOST: redis-{{ env }}.daws86.fun
CATALOGUE_HOST: catalogue-{{ env }}.daws86.fun
CART_HOST: cart-{{ env }}.daws86.fun
USER_HOST: user-{{ env }}.daws86.fun
RABBITMQ_HOST: rabbitmq-{{ env }}.daws86.fun
MYSQL_HOST: mysql-{{ env }}.daws86.fun
SHIPPING_HOST: shipping-{{ env }}.daws86.fun
PAYMENT_HOST: payment-{{ env }}.daws86.fun